{
 "title": "Docker monitoring",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [ "docker" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": ".99 percentile METRIC_NAME",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "quantile_over_time(0.99, {job = \"web-service\"} | json | line_format \"{{.log}}\" | json | value_metricName = \"METRIC_NAME\" | unwrap value_metricValue [$__interval]) by (apiName)"
    }
   ]
  },
  {
   "title": ".95 percentile METRIC_NAME",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "quantile_over_time(0.95, {job = \"web-service\"} | json | line_format \"{{.log}}\" | json | value_metricName = \"METRIC_NAME\" | unwrap value_metricValue [$__interval]) by (apiName)"
    }
   ]
  },
  {
   "title": ".50 percentile METRIC_NAME",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "quantile_over_time(0.50, {job = \"web-service\"} | json | line_format \"{{.log}}\" | json | value_metricName = \"METRIC_NAME\" | unwrap value_metricValue [$__interval]) by (apiName)"
    }
   ]
  },
  {
   "title": "avg over time METRIC_NAME",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "avg_over_time({job = \"web-service\"} | json | line_format \"{{.log}}\" | json | value_metricName = \"METRIC_NAME\" | unwrap value_metricValue [$__interval]) by (apiName)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "web Service CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{name=~\"web-benchmark-web-service-service-.*\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "web Service Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"web-benchmark-web-service-service-.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{image!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{image!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}